name = "PHYS5315"
uuid = "8a4b2cf9-767f-4f8f-a8fc-166d83d31b20"
authors = ["John Waczak", "David Lary"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
